/// Abstract interface for embedding providers (Gemini, OpenAI, local, etc.)
abstract class EmbeddingsAdapter {
  /// Generates an embedding vector for the given text.
  Future<List<double>> embed(String text);

  /// The dimension of the embeddings generated by this adapter.
  int get dimension;

  /// Optionally, provider/model name.
  String get providerName;
}
