/// Abstract interface for embedding providers (Gemini, OpenAI, local, etc.)
abstract class EmbeddingsAdapter {
  /// Generates an embedding vector for the given text.
  Future<List<double>> embed(String text);

  /// Generates a normalized embedding for medical domain text.
  /// Default implementation just calls [embed].
  Future<List<double>> medicalNormalized(String text) => embed(text);

  /// The dimension of the embeddings generated by this adapter.
  int get dimension;

  /// Optionally, provider/model name.
  String get providerName;
}
