name: Publish to pub.dev (sanity)

on:
  push:
    branches:
      - ci/fix-publish-workflow-conditions

jobs:
  sanity:
    name: Sanity
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "sanity ok"
